// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#ifndef UI_AUTO_DIM_SWITCH_H
#define UI_AUTO_DIM_SWITCH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Auto_Dim_Switch
extern void ui_Auto_Dim_Switch_screen_init(void);
extern void ui_Auto_Dim_Switch_screen_destroy(void);
extern void ui_event_Auto_Dim_Switch(lv_event_t * e);
extern lv_obj_t * ui_Auto_Dim_Switch;
extern void ui_event_Brightness_Slider(lv_event_t * e);
extern lv_obj_t * ui_Brightness_Slider;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern void ui_event_Auto_dim_Roller(lv_event_t * e);
extern lv_obj_t * ui_Auto_dim_Roller;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

