// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#include "ui.h"

lv_obj_t * ui_App_Settings = NULL;
lv_obj_t * ui_uiHighPassSlider = NULL;
lv_obj_t * ui_uiNoiseVolumeSlider = NULL;
lv_obj_t * ui_uieventnoiseTypeRadioGroup = NULL;
lv_obj_t * ui_uiNoiseMaskingSwitch = NULL;
lv_obj_t * ui_uiBinauralBeatsSwitch_ = NULL;
lv_obj_t * ui_uiBinauralVolumeSlider_ = NULL;
lv_obj_t * ui_uiBinauralModeRadioGroup = NULL;
lv_obj_t * ui_uilowPassSlider = NULL;
lv_obj_t * ui_uiFilterBypassSwitch = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions
void ui_event_App_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_uiHighPassSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_highPassSlider(e);
    }
}

void ui_event_uiNoiseVolumeSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_noiseVolumeSlider(e);
    }
}

void ui_event_uieventnoiseTypeRadioGroup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_NoiseTypeRadioGroup(e);
    }
}

void ui_event_uiNoiseMaskingSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_noiseMaskingSwitch(e);
    }
}

void ui_event_uiBinauralBeatsSwitch_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_binauralBeatsSwitch(e);
    }
}

void ui_event_uiBinauralVolumeSlider_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_binauralVolumeSlider(e);
    }
}

void ui_event_uiBinauralModeRadioGroup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_binauralModeRadioGroup(e);
    }
}

void ui_event_uilowPassSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_lowPassSlider(e);
    }
}

void ui_event_uiFilterBypassSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_filterBypassSwitch(e);
    }
}

// build funtions

void ui_App_Settings_screen_init(void)
{
    ui_App_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_App_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_App_Settings, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_App_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiHighPassSlider = lv_slider_create(ui_App_Settings);
    lv_slider_set_value(ui_uiHighPassSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_uiHighPassSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_uiHighPassSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_uiHighPassSlider, 150);
    lv_obj_set_height(ui_uiHighPassSlider, 10);
    lv_obj_set_x(ui_uiHighPassSlider, 9);
    lv_obj_set_y(ui_uiHighPassSlider, 68);
    lv_obj_set_align(ui_uiHighPassSlider, LV_ALIGN_CENTER);

    ui_uiNoiseVolumeSlider = lv_slider_create(ui_App_Settings);
    lv_slider_set_value(ui_uiNoiseVolumeSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_uiNoiseVolumeSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_uiNoiseVolumeSlider,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(ui_uiNoiseVolumeSlider, 150);
    lv_obj_set_height(ui_uiNoiseVolumeSlider, 10);
    lv_obj_set_x(ui_uiNoiseVolumeSlider, 12);
    lv_obj_set_y(ui_uiNoiseVolumeSlider, -77);
    lv_obj_set_align(ui_uiNoiseVolumeSlider, LV_ALIGN_CENTER);

    ui_uieventnoiseTypeRadioGroup = lv_roller_create(ui_App_Settings);
    lv_roller_set_options(ui_uieventnoiseTypeRadioGroup, "Pink Noise\nBrown Noise", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_uieventnoiseTypeRadioGroup, 30);
    lv_obj_set_width(ui_uieventnoiseTypeRadioGroup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_uieventnoiseTypeRadioGroup, 6);
    lv_obj_set_y(ui_uieventnoiseTypeRadioGroup, -106);
    lv_obj_set_align(ui_uieventnoiseTypeRadioGroup, LV_ALIGN_CENTER);

    ui_uiNoiseMaskingSwitch = lv_switch_create(ui_App_Settings);
    lv_obj_set_width(ui_uiNoiseMaskingSwitch, 50);
    lv_obj_set_height(ui_uiNoiseMaskingSwitch, 25);
    lv_obj_set_x(ui_uiNoiseMaskingSwitch, -113);
    lv_obj_set_y(ui_uiNoiseMaskingSwitch, -77);
    lv_obj_set_align(ui_uiNoiseMaskingSwitch, LV_ALIGN_CENTER);

    ui_uiBinauralBeatsSwitch_ = lv_switch_create(ui_App_Settings);
    lv_obj_set_width(ui_uiBinauralBeatsSwitch_, 50);
    lv_obj_set_height(ui_uiBinauralBeatsSwitch_, 25);
    lv_obj_set_x(ui_uiBinauralBeatsSwitch_, -112);
    lv_obj_set_y(ui_uiBinauralBeatsSwitch_, 9);
    lv_obj_set_align(ui_uiBinauralBeatsSwitch_, LV_ALIGN_CENTER);

    ui_uiBinauralVolumeSlider_ = lv_slider_create(ui_App_Settings);
    lv_slider_set_value(ui_uiBinauralVolumeSlider_, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_uiBinauralVolumeSlider_) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_uiBinauralVolumeSlider_, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_uiBinauralVolumeSlider_, 150);
    lv_obj_set_height(ui_uiBinauralVolumeSlider_, 10);
    lv_obj_set_x(ui_uiBinauralVolumeSlider_, 10);
    lv_obj_set_y(ui_uiBinauralVolumeSlider_, 12);
    lv_obj_set_align(ui_uiBinauralVolumeSlider_, LV_ALIGN_CENTER);

    ui_uiBinauralModeRadioGroup = lv_roller_create(ui_App_Settings);
    lv_roller_set_options(ui_uiBinauralModeRadioGroup, "DeepRelax\nTrance\nCalmFocus\nAlertness\nHeightenedPerception",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_uiBinauralModeRadioGroup, 30);
    lv_obj_set_width(ui_uiBinauralModeRadioGroup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_uiBinauralModeRadioGroup, 8);
    lv_obj_set_y(ui_uiBinauralModeRadioGroup, -19);
    lv_obj_set_align(ui_uiBinauralModeRadioGroup, LV_ALIGN_CENTER);

    ui_uilowPassSlider = lv_slider_create(ui_App_Settings);
    lv_slider_set_value(ui_uilowPassSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_uilowPassSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_uilowPassSlider, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_uilowPassSlider, 150);
    lv_obj_set_height(ui_uilowPassSlider, 10);
    lv_obj_set_x(ui_uilowPassSlider, 9);
    lv_obj_set_y(ui_uilowPassSlider, 96);
    lv_obj_set_align(ui_uilowPassSlider, LV_ALIGN_CENTER);

    ui_uiFilterBypassSwitch = lv_switch_create(ui_App_Settings);
    lv_obj_set_width(ui_uiFilterBypassSwitch, 50);
    lv_obj_set_height(ui_uiFilterBypassSwitch, 25);
    lv_obj_set_x(ui_uiFilterBypassSwitch, -111);
    lv_obj_set_y(ui_uiFilterBypassSwitch, 81);
    lv_obj_set_align(ui_uiFilterBypassSwitch, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 5);
    lv_obj_set_y(ui_Label10, -135);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Noise Masking");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 7);
    lv_obj_set_y(ui_Label11, -50);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Binural Beats");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 6);
    lv_obj_set_y(ui_Label12, 44);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Filters");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 107);
    lv_obj_set_y(ui_Label13, -77);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Vol");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 105);
    lv_obj_set_y(ui_Label5, 96);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "LF");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 109);
    lv_obj_set_y(ui_Label6, 12);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Vol");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 107);
    lv_obj_set_y(ui_Label7, 69);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "HF");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_uiHighPassSlider, ui_event_uiHighPassSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiNoiseVolumeSlider, ui_event_uiNoiseVolumeSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uieventnoiseTypeRadioGroup, ui_event_uieventnoiseTypeRadioGroup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiNoiseMaskingSwitch, ui_event_uiNoiseMaskingSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiBinauralBeatsSwitch_, ui_event_uiBinauralBeatsSwitch_, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiBinauralVolumeSlider_, ui_event_uiBinauralVolumeSlider_, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiBinauralModeRadioGroup, ui_event_uiBinauralModeRadioGroup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uilowPassSlider, ui_event_uilowPassSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiFilterBypassSwitch, ui_event_uiFilterBypassSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_App_Settings, ui_event_App_Settings, LV_EVENT_ALL, NULL);

}

void ui_App_Settings_screen_destroy(void)
{
    if(ui_App_Settings) lv_obj_del(ui_App_Settings);

    // NULL screen variables
    ui_App_Settings = NULL;
    ui_uiHighPassSlider = NULL;
    ui_uiNoiseVolumeSlider = NULL;
    ui_uieventnoiseTypeRadioGroup = NULL;
    ui_uiNoiseMaskingSwitch = NULL;
    ui_uiBinauralBeatsSwitch_ = NULL;
    ui_uiBinauralVolumeSlider_ = NULL;
    ui_uiBinauralModeRadioGroup = NULL;
    ui_uilowPassSlider = NULL;
    ui_uiFilterBypassSwitch = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;

}
