// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#ifndef UI_APP_SETTINGS_H
#define UI_APP_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_App_Settings
extern void ui_App_Settings_screen_init(void);
extern void ui_App_Settings_screen_destroy(void);
extern void ui_event_App_Settings(lv_event_t * e);
extern lv_obj_t * ui_App_Settings;
extern void ui_event_uiHighPassSlider(lv_event_t * e);
extern lv_obj_t * ui_uiHighPassSlider;
extern void ui_event_uiNoiseVolumeSlider(lv_event_t * e);
extern lv_obj_t * ui_uiNoiseVolumeSlider;
extern void ui_event_uieventnoiseTypeRadioGroup(lv_event_t * e);
extern lv_obj_t * ui_uieventnoiseTypeRadioGroup;
extern void ui_event_uiNoiseMaskingSwitch(lv_event_t * e);
extern lv_obj_t * ui_uiNoiseMaskingSwitch;
extern void ui_event_uiBinauralBeatsSwitch_(lv_event_t * e);
extern lv_obj_t * ui_uiBinauralBeatsSwitch_;
extern void ui_event_uiBinauralVolumeSlider_(lv_event_t * e);
extern lv_obj_t * ui_uiBinauralVolumeSlider_;
extern void ui_event_uiBinauralModeRadioGroup(lv_event_t * e);
extern lv_obj_t * ui_uiBinauralModeRadioGroup;
extern void ui_event_uilowPassSlider(lv_event_t * e);
extern lv_obj_t * ui_uilowPassSlider;
extern void ui_event_uiFilterBypassSwitch(lv_event_t * e);
extern lv_obj_t * ui_uiFilterBypassSwitch;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

