// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#include "ui.h"

lv_obj_t * ui_Auto_Dim_Switch = NULL;
lv_obj_t * ui_Brightness_Slider = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Auto_dim_Roller = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_Auto_Dim_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_Brightness_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_brightness_slider_changed(e);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_auto_dim_toggle_changed(e);
    }
}

void ui_event_Auto_dim_Roller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_timeout_dropdown_changed(e);
    }
}

// build funtions

void ui_Auto_Dim_Switch_screen_init(void)
{
    ui_Auto_Dim_Switch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Auto_Dim_Switch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Auto_Dim_Switch, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Auto_Dim_Switch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brightness_Slider = lv_slider_create(ui_Auto_Dim_Switch);
    lv_slider_set_value(ui_Brightness_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Brightness_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Brightness_Slider, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_Brightness_Slider, 150);
    lv_obj_set_height(ui_Brightness_Slider, 10);
    lv_obj_set_x(ui_Brightness_Slider, 52);
    lv_obj_set_y(ui_Brightness_Slider, 38);
    lv_obj_set_align(ui_Brightness_Slider, LV_ALIGN_CENTER);

    ui_Switch1 = lv_switch_create(ui_Auto_Dim_Switch);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -25);
    lv_obj_set_y(ui_Switch1, -18);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Auto_dim_Roller = lv_roller_create(ui_Auto_Dim_Switch);
    lv_roller_set_options(ui_Auto_dim_Roller, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Auto_dim_Roller, 36);
    lv_obj_set_width(ui_Auto_dim_Roller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Auto_dim_Roller, 66);
    lv_obj_set_y(ui_Auto_dim_Roller, -17);
    lv_obj_set_align(ui_Auto_dim_Roller, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_Auto_Dim_Switch);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -91);
    lv_obj_set_y(ui_Label2, 37);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Brightness");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Auto_Dim_Switch);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -102);
    lv_obj_set_y(ui_Label3, -18);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Auto-Dim");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Brightness_Slider, ui_event_Brightness_Slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Auto_dim_Roller, ui_event_Auto_dim_Roller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Auto_Dim_Switch, ui_event_Auto_Dim_Switch, LV_EVENT_ALL, NULL);

}

void ui_Auto_Dim_Switch_screen_destroy(void)
{
    if(ui_Auto_Dim_Switch) lv_obj_del(ui_Auto_Dim_Switch);

    // NULL screen variables
    ui_Auto_Dim_Switch = NULL;
    ui_Brightness_Slider = NULL;
    ui_Switch1 = NULL;
    ui_Auto_dim_Roller = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;

}
