// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#include "ui.h"

void MuteButton(lv_event_t * e)
{
	// Your code here
}

void on_ptt_switch_changed(lv_event_t * e)
{
	// Your code here
}

void ui_event_playThroughSwitch(lv_event_t * e)
{
	// Your code here
}

void ui_event_gainSlider(lv_event_t * e)
{
	// Your code here
}

void ui_BluetoothStatusLabel(lv_event_t * e)
{
	// Your code here
}

void on_brightness_slider_changed(lv_event_t * e)
{
	// Your code here
}

void on_auto_dim_toggle_changed(lv_event_t * e)
{
	// Your code here
}

void on_timeout_dropdown_changed(lv_event_t * e)
{
	// Your code here
}

void ui_event_highPassSlider(lv_event_t * e)
{
	// Your code here
}

void ui_event_noiseVolumeSlider(lv_event_t * e)
{
	// Your code here
}

void ui_NoiseTypeRadioGroup(lv_event_t * e)
{
	// Your code here
}

void ui_event_noiseMaskingSwitch(lv_event_t * e)
{
	// Your code here
}

void ui_event_binauralBeatsSwitch(lv_event_t * e)
{
	// Your code here
}

void ui_event_binauralVolumeSlider(lv_event_t * e)
{
	// Your code here
}

void ui_event_binauralModeRadioGroup(lv_event_t * e)
{
	// Your code here
}

void ui_event_lowPassSlider(lv_event_t * e)
{
	// Your code here
}

void ui_event_filterBypassSwitch(lv_event_t * e)
{
	// Your code here
}

/**
 * @brief BLE Mute Function
 * 
 * This function handles muting functionality via Bluetooth.
 * Called from the UI event handlers when mute button is triggered.
 * 
 * TODO: Implement actual BLE communication to send mute command
 */
void ble_mute_from_ui(void)
{
	// Your code here - implement BLE mute functionality
}
