// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_mute_button_event(lv_event_t * e);
void on_ptt_switch_changed(lv_event_t * e);
void ui_event_playThroughSwitch(lv_event_t * e);
void ui_event_gainSlider(lv_event_t * e);
void ui_BluetoothStatusLabel(lv_event_t * e);
void on_brightness_slider_changed(lv_event_t * e);
void on_auto_dim_toggle_changed(lv_event_t * e);
void on_timeout_dropdown_changed(lv_event_t * e);
void ui_event_highPassSlider(lv_event_t * e);
void ui_event_noiseVolumeSlider(lv_event_t * e);
void ui_NoiseTypeRadioGroup(lv_event_t * e);
void ui_event_noiseMaskingSwitch(lv_event_t * e);
void ui_event_binauralBeatsSwitch(lv_event_t * e);
void ui_event_binauralVolumeSlider(lv_event_t * e);
void ui_event_binauralModeRadioGroup(lv_event_t * e);
void ui_event_lowPassSlider(lv_event_t * e);
void ui_event_filterBypassSwitch(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
