// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#include "ui.h"

void MuteButton(lv_event_t * e)
{
	// Call bluetooth mute function
	ble_mute_from_ui();
}

void on_ptt_switch_changed(lv_event_t * e)
{
	// Get the switch object
	lv_obj_t * switch_obj = lv_event_get_target(e);
	
	// Get the switch state (checked = 1, unchecked = 0)
	int state = lv_obj_has_state(switch_obj, LV_STATE_CHECKED) ? 1 : 0;
	
	// Send PTT state via bluetooth
	ble_ptt_from_ui(state);
}

void ui_event_playThroughSwitch(lv_event_t * e)
{
	// Your code here
}

void ui_event_gainSlider(lv_event_t * e)
{
	// Your code here
}

void ui_BluetoothStatusLabel(lv_event_t * e)
{
	// Update bluetooth status display
	ble_update_status_ui();
}

void on_brightness_slider_changed(lv_event_t * e)
{
	// Your code here
}

void on_auto_dim_toggle_changed(lv_event_t * e)
{
	// Your code here
}

void on_timeout_dropdown_changed(lv_event_t * e)
{
	// Your code here
}

void ui_event_highPassSlider(lv_event_t * e)
{
	// Your code here
}

void ui_event_noiseVolumeSlider(lv_event_t * e)
{
	// Your code here
}

void ui_NoiseTypeRadioGroup(lv_event_t * e)
{
	// Your code here
}

void ui_event_noiseMaskingSwitch(lv_event_t * e)
{
	// Your code here
}

void ui_event_binauralBeatsSwitch(lv_event_t * e)
{
	// Your code here
}

void ui_event_binauralVolumeSlider(lv_event_t * e)
{
	// Your code here
}

void ui_event_binauralModeRadioGroup(lv_event_t * e)
{
	// Your code here
}

void ui_event_lowPassSlider(lv_event_t * e)
{
	// Your code here
}

void ui_event_filterBypassSwitch(lv_event_t * e)
{
	// Your code here
}

void onMicGainArcChanged(lv_event_t * e)
{
	// Your code here
}

void onHFSliderChanged(lv_event_t * e)
{
	// Your code here
}

void NoiseMaskingVolumeSlider(lv_event_t * e)
{
	// Your code here
}

void onNoiseMaskingModeChanged(lv_event_t * e)
{
	// Your code here
}

void onNoiseMaskingSwitchChanged(lv_event_t * e)
{
	// Your code here
}

void onBinauralBeatsSwitchChanged(lv_event_t * e)
{
	// Your code here
}

void BinauralBeatsIntensitySlider(lv_event_t * e)
{
	// Your code here
}

void ui_event_Binural_Roller(lv_event_t * e)
{
	// Your code here
}

void onLFSliderChanged(lv_event_t * e)
{
	// Your code here
}

void onFiltersSwitchChanged(lv_event_t * e)
{
	// Your code here
}

/**
 * @brief BLE Mute Function
 * 
 * This function handles muting functionality via Bluetooth.
 * Called from the UI event handlers when mute button is triggered.
 * 
 * TODO: Implement actual BLE communication to send mute command
 */
void ble_mute_from_ui(void)
{
	// Your code here - implement BLE mute functionality
}

/**
 * @brief BLE PTT (Push-to-Talk) Function
 * 
 * This function handles PTT state changes via Bluetooth.
 * Called when the PTT switch is toggled in the UI.
 * 
 * @param state The PTT state: 1 for active (pushed), 0 for inactive (released)
 * 
 * TODO: Implement actual BLE communication to send PTT state
 */
void ble_ptt_from_ui(int state)
{
	// Your code here - implement BLE PTT functionality
	// Example: Send PTT command via BLE with the state parameter
}

/**
 * @brief Update Bluetooth Status UI
 * 
 * This function updates the bluetooth status display in the UI.
 * Should be called when bluetooth connection status changes.
 * 
 * TODO: Implement BLE status reading and UI update
 */
void ble_update_status_ui(void)
{
	// Your code here - implement BLE status update
	// Example: Read BLE connection status and update ui_uiBluetoothStatusLabel
}
