// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Label1;
extern void ui_event_Mute_Button(lv_event_t * e);
extern lv_obj_t * ui_Mute_Button;
extern void ui_event_PTT(lv_event_t * e);
extern lv_obj_t * ui_PTT;
extern void ui_event_uiPlayThroughSwitch(lv_event_t * e);
extern lv_obj_t * ui_uiPlayThroughSwitch;
extern void ui_event_uiGainSlider(lv_event_t * e);
extern lv_obj_t * ui_uiGainSlider;
extern lv_obj_t * ui_Battery_level;
extern lv_obj_t * ui_Usb_Status;
extern void ui_event_uiBluetoothStatusLabel(lv_event_t * e);
extern lv_obj_t * ui_uiBluetoothStatusLabel;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

