// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#include "ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Mute_Button = NULL;
lv_obj_t * ui_PTT = NULL;
lv_obj_t * ui_uiPlayThroughSwitch = NULL;
lv_obj_t * ui_uiGainSlider = NULL;
lv_obj_t * ui_Battery_level = NULL;
lv_obj_t * ui_Usb_Status = NULL;
lv_obj_t * ui_uiBluetoothStatusLabel = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions
void ui_event_Main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Auto_Dim_Switch, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Auto_Dim_Switch_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_App_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_App_Settings_screen_init);
    }
}

void ui_event_Mute_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        (e);
        MuteButton(e);
    }
}

void ui_event_PTT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_ptt_switch_changed(e);
    }
}

void ui_event_uiPlayThroughSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_playThroughSwitch(e);
    }
}

void ui_event_uiGainSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_gainSlider(e);
    }
}

void ui_event_uiBluetoothStatusLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_BluetoothStatusLabel(e);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scroll_dir(ui_Main, LV_DIR_BOTTOM);
    lv_obj_set_scroll_snap_x(ui_Main, LV_SCROLL_SNAP_START);
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x12E522), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -7);
    lv_obj_set_y(ui_Label1, -2);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "text");

    ui_Mute_Button = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Mute_Button, 100);
    lv_obj_set_height(ui_Mute_Button, 50);
    lv_obj_set_align(ui_Mute_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Mute_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Mute_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PTT = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_PTT, 50);
    lv_obj_set_height(ui_PTT, 25);
    lv_obj_set_x(ui_PTT, 6);
    lv_obj_set_y(ui_PTT, 128);
    lv_obj_set_align(ui_PTT, LV_ALIGN_CENTER);

    ui_uiPlayThroughSwitch = lv_switch_create(ui_Main);
    lv_obj_set_width(ui_uiPlayThroughSwitch, 50);
    lv_obj_set_height(ui_uiPlayThroughSwitch, 25);
    lv_obj_set_x(ui_uiPlayThroughSwitch, 6);
    lv_obj_set_y(ui_uiPlayThroughSwitch, 90);
    lv_obj_set_align(ui_uiPlayThroughSwitch, LV_ALIGN_CENTER);

    ui_uiGainSlider = lv_spinner_create(ui_Main, 1000, 90);
    lv_obj_set_width(ui_uiGainSlider, 347);
    lv_obj_set_height(ui_uiGainSlider, 342);
    lv_obj_set_x(ui_uiGainSlider, 3);
    lv_obj_set_y(ui_uiGainSlider, 1);
    lv_obj_set_align(ui_uiGainSlider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiGainSlider, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Battery_level = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Battery_level, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery_level, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery_level, -2);
    lv_obj_set_y(ui_Battery_level, -135);
    lv_obj_set_align(ui_Battery_level, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Battery_level, "text");
    lv_obj_set_style_text_color(ui_Battery_level, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Battery_level, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Usb_Status = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Usb_Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Usb_Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Usb_Status, 41);
    lv_obj_set_y(ui_Usb_Status, -135);
    lv_obj_set_align(ui_Usb_Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Usb_Status, "text");
    lv_obj_set_style_text_color(ui_Usb_Status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Usb_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiBluetoothStatusLabel = lv_label_create(ui_Main);
    lv_obj_set_width(ui_uiBluetoothStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiBluetoothStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiBluetoothStatusLabel, -46);
    lv_obj_set_y(ui_uiBluetoothStatusLabel, -135);
    lv_obj_set_align(ui_uiBluetoothStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiBluetoothStatusLabel, "text");
    lv_obj_set_style_text_color(ui_uiBluetoothStatusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiBluetoothStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -60);
    lv_obj_set_y(ui_Label4, 91);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Talkover");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -47);
    lv_obj_set_y(ui_Label8, 129);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "PTT");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "text");

    lv_obj_add_event_cb(ui_Mute_Button, ui_event_Mute_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PTT, ui_event_PTT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiPlayThroughSwitch, ui_event_uiPlayThroughSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiGainSlider, ui_event_uiGainSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiBluetoothStatusLabel, ui_event_uiBluetoothStatusLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main, ui_event_Main, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_Label1 = NULL;
    ui_Mute_Button = NULL;
    ui_PTT = NULL;
    ui_uiPlayThroughSwitch = NULL;
    ui_uiGainSlider = NULL;
    ui_Battery_level = NULL;
    ui_Usb_Status = NULL;
    ui_uiBluetoothStatusLabel = NULL;
    ui_Label4 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;

}
