// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#include "ui.h"

lv_obj_t * ui_App_Settings = NULL;
lv_obj_t * ui_Filter_HF_Slider = NULL;
lv_obj_t * ui_Noise_Mask_slider = NULL;
lv_obj_t * ui_Noise_Mask_Roller = NULL;
lv_obj_t * ui_Noise_Mask_Switch = NULL;
lv_obj_t * ui_Binural_Switch = NULL;
lv_obj_t * ui_Binural_Slider = NULL;
lv_obj_t * ui_Binural_Roller = NULL;
lv_obj_t * ui_Filter_LF_Slider = NULL;
lv_obj_t * ui_Filter_Switch = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions
void ui_event_App_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_Filter_HF_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onHFSliderChanged(e);
    }
}

void ui_event_Noise_Mask_slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        NoiseMaskingVolumeSlider(e);
    }
}

void ui_event_Noise_Mask_Roller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onNoiseMaskingModeChanged(e);
    }
}

void ui_event_Noise_Mask_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onNoiseMaskingSwitchChanged(e);
    }
}

void ui_event_Binural_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onBinauralBeatsSwitchChanged(e);
    }
}

void ui_event_Binural_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        BinauralBeatsIntensitySlider(e);
    }
}

void ui_event_Binural_Roller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_Binural_Roller(e);
    }
}

void ui_event_Filter_LF_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onLFSliderChanged(e);
    }
}

void ui_event_Filter_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onFiltersSwitchChanged(e);
    }
}

// build funtions

void ui_App_Settings_screen_init(void)
{
    ui_App_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_App_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_App_Settings, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_App_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Filter_HF_Slider = lv_slider_create(ui_App_Settings);
    lv_slider_set_value(ui_Filter_HF_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Filter_HF_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Filter_HF_Slider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_Filter_HF_Slider, 150);
    lv_obj_set_height(ui_Filter_HF_Slider, 10);
    lv_obj_set_x(ui_Filter_HF_Slider, 9);
    lv_obj_set_y(ui_Filter_HF_Slider, 68);
    lv_obj_set_align(ui_Filter_HF_Slider, LV_ALIGN_CENTER);

    ui_Noise_Mask_slider = lv_slider_create(ui_App_Settings);
    lv_slider_set_value(ui_Noise_Mask_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Noise_Mask_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Noise_Mask_slider, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_Noise_Mask_slider, 150);
    lv_obj_set_height(ui_Noise_Mask_slider, 10);
    lv_obj_set_x(ui_Noise_Mask_slider, 12);
    lv_obj_set_y(ui_Noise_Mask_slider, -77);
    lv_obj_set_align(ui_Noise_Mask_slider, LV_ALIGN_CENTER);

    ui_Noise_Mask_Roller = lv_roller_create(ui_App_Settings);
    lv_roller_set_options(ui_Noise_Mask_Roller, "Pink Noise\nBrown Noise", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Noise_Mask_Roller, 30);
    lv_obj_set_width(ui_Noise_Mask_Roller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Noise_Mask_Roller, 6);
    lv_obj_set_y(ui_Noise_Mask_Roller, -106);
    lv_obj_set_align(ui_Noise_Mask_Roller, LV_ALIGN_CENTER);

    ui_Noise_Mask_Switch = lv_switch_create(ui_App_Settings);
    lv_obj_set_width(ui_Noise_Mask_Switch, 50);
    lv_obj_set_height(ui_Noise_Mask_Switch, 25);
    lv_obj_set_x(ui_Noise_Mask_Switch, -113);
    lv_obj_set_y(ui_Noise_Mask_Switch, -77);
    lv_obj_set_align(ui_Noise_Mask_Switch, LV_ALIGN_CENTER);

    ui_Binural_Switch = lv_switch_create(ui_App_Settings);
    lv_obj_set_width(ui_Binural_Switch, 50);
    lv_obj_set_height(ui_Binural_Switch, 25);
    lv_obj_set_x(ui_Binural_Switch, -112);
    lv_obj_set_y(ui_Binural_Switch, 9);
    lv_obj_set_align(ui_Binural_Switch, LV_ALIGN_CENTER);

    ui_Binural_Slider = lv_slider_create(ui_App_Settings);
    lv_slider_set_value(ui_Binural_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Binural_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Binural_Slider, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_Binural_Slider, 150);
    lv_obj_set_height(ui_Binural_Slider, 10);
    lv_obj_set_x(ui_Binural_Slider, 10);
    lv_obj_set_y(ui_Binural_Slider, 12);
    lv_obj_set_align(ui_Binural_Slider, LV_ALIGN_CENTER);

    ui_Binural_Roller = lv_roller_create(ui_App_Settings);
    lv_roller_set_options(ui_Binural_Roller, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Binural_Roller, 30);
    lv_obj_set_width(ui_Binural_Roller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Binural_Roller, 8);
    lv_obj_set_y(ui_Binural_Roller, -19);
    lv_obj_set_align(ui_Binural_Roller, LV_ALIGN_CENTER);

    ui_Filter_LF_Slider = lv_slider_create(ui_App_Settings);
    lv_slider_set_value(ui_Filter_LF_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Filter_LF_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Filter_LF_Slider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_Filter_LF_Slider, 150);
    lv_obj_set_height(ui_Filter_LF_Slider, 10);
    lv_obj_set_x(ui_Filter_LF_Slider, 9);
    lv_obj_set_y(ui_Filter_LF_Slider, 96);
    lv_obj_set_align(ui_Filter_LF_Slider, LV_ALIGN_CENTER);

    ui_Filter_Switch = lv_switch_create(ui_App_Settings);
    lv_obj_set_width(ui_Filter_Switch, 50);
    lv_obj_set_height(ui_Filter_Switch, 25);
    lv_obj_set_x(ui_Filter_Switch, -111);
    lv_obj_set_y(ui_Filter_Switch, 81);
    lv_obj_set_align(ui_Filter_Switch, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 5);
    lv_obj_set_y(ui_Label10, -135);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Noise Masking");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 7);
    lv_obj_set_y(ui_Label11, -50);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Binural Beats");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 6);
    lv_obj_set_y(ui_Label12, 44);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Filters");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 107);
    lv_obj_set_y(ui_Label13, -77);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Vol");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 105);
    lv_obj_set_y(ui_Label5, 96);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "LF");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 109);
    lv_obj_set_y(ui_Label6, 12);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Vol");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_App_Settings);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 107);
    lv_obj_set_y(ui_Label7, 69);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "HF");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Filter_HF_Slider, ui_event_Filter_HF_Slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Noise_Mask_slider, ui_event_Noise_Mask_slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Noise_Mask_Roller, ui_event_Noise_Mask_Roller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Noise_Mask_Switch, ui_event_Noise_Mask_Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Binural_Switch, ui_event_Binural_Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Binural_Slider, ui_event_Binural_Slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Binural_Roller, ui_event_Binural_Roller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Filter_LF_Slider, ui_event_Filter_LF_Slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Filter_Switch, ui_event_Filter_Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_App_Settings, ui_event_App_Settings, LV_EVENT_ALL, NULL);

}

void ui_App_Settings_screen_destroy(void)
{
    if(ui_App_Settings) lv_obj_del(ui_App_Settings);

    // NULL screen variables
    ui_App_Settings = NULL;
    ui_Filter_HF_Slider = NULL;
    ui_Noise_Mask_slider = NULL;
    ui_Noise_Mask_Roller = NULL;
    ui_Noise_Mask_Switch = NULL;
    ui_Binural_Switch = NULL;
    ui_Binural_Slider = NULL;
    ui_Binural_Roller = NULL;
    ui_Filter_LF_Slider = NULL;
    ui_Filter_Switch = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;

}
