// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#ifndef UI_APP_SETTINGS_H
#define UI_APP_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_App_Settings
extern void ui_App_Settings_screen_init(void);
extern void ui_App_Settings_screen_destroy(void);
extern void ui_event_App_Settings(lv_event_t * e);
extern lv_obj_t * ui_App_Settings;
extern void ui_event_Filter_HF_Slider(lv_event_t * e);
extern lv_obj_t * ui_Filter_HF_Slider;
extern void ui_event_Noise_Mask_slider(lv_event_t * e);
extern lv_obj_t * ui_Noise_Mask_slider;
extern void ui_event_Noise_Mask_Roller(lv_event_t * e);
extern lv_obj_t * ui_Noise_Mask_Roller;
extern void ui_event_Noise_Mask_Switch(lv_event_t * e);
extern lv_obj_t * ui_Noise_Mask_Switch;
extern void ui_event_Binural_Switch(lv_event_t * e);
extern lv_obj_t * ui_Binural_Switch;
extern void ui_event_Binural_Slider(lv_event_t * e);
extern lv_obj_t * ui_Binural_Slider;
extern void ui_event_Binural_Roller(lv_event_t * e);
extern lv_obj_t * ui_Binural_Roller;
extern void ui_event_Filter_LF_Slider(lv_event_t * e);
extern lv_obj_t * ui_Filter_LF_Slider;
extern void ui_event_Filter_Switch(lv_event_t * e);
extern lv_obj_t * ui_Filter_Switch;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

