// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#include "ui.h"

void on_mute_button_click(lv_event_t * e)
{
	// Your code here
}

void on_ptt_switch_changed(lv_event_t * e)
{
	// Your code here
}

void onMicGainArcChanged(lv_event_t * e)
{
	// Your code here
}

void on_brightness_slider_changed(lv_event_t * e)
{
	// Your code here
}

void on_auto_dim_toggle_changed(lv_event_t * e)
{
	// Your code here
}

void on_timeout_dropdown_changed(lv_event_t * e)
{
	// Your code here
}

void onHFSliderChanged(lv_event_t * e)
{
	// Your code here
}

void NoiseMaskingVolumeSlider(lv_event_t * e)
{
	// Your code here
}

void onNoiseMaskingModeChanged(lv_event_t * e)
{
	// Your code here
}

void onNoiseMaskingSwitchChanged(lv_event_t * e)
{
	// Your code here
}

void onBinauralBeatsSwitchChanged(lv_event_t * e)
{
	// Your code here
}

void BinauralBeatsIntensitySlider(lv_event_t * e)
{
	// Your code here
}

void ui_event_Binural_Roller(lv_event_t * e)
{
	// Your code here
}

void onLFSliderChanged(lv_event_t * e)
{
	// Your code here
}

void onFiltersSwitchChanged(lv_event_t * e)
{
	// Your code here
}
