// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: remote

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_mute_button_click(lv_event_t * e);
void on_ptt_switch_changed(lv_event_t * e);
void onMicGainArcChanged(lv_event_t * e);
void on_brightness_slider_changed(lv_event_t * e);
void on_auto_dim_toggle_changed(lv_event_t * e);
void on_timeout_dropdown_changed(lv_event_t * e);
void onHFSliderChanged(lv_event_t * e);
void NoiseMaskingVolumeSlider(lv_event_t * e);
void onNoiseMaskingModeChanged(lv_event_t * e);
void onNoiseMaskingSwitchChanged(lv_event_t * e);
void onBinauralBeatsSwitchChanged(lv_event_t * e);
void BinauralBeatsIntensitySlider(lv_event_t * e);
void ui_event_Binural_Roller(lv_event_t * e);
void onLFSliderChanged(lv_event_t * e);
void onFiltersSwitchChanged(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
